package ba.tfb.tasknest.entity.enums;

public enum NotificationType {
    NEW_TASK_IN_AREA,
    NEW_OFFER,
    OFFER_ACCEPTED,
    NEW_MESSAGE,
    TASK_STARTED,
    TASK_COMPLETED,
    TASK_CLOSED,
    TASK_EXPIRED,
    REVIEW_RECEIVED,
    TASK_REMOVED,
    TASKER_WITHDREW,
    ASSIGNMENT_RELEASED,
    OFFER_REACTIVATED,
    ASSIGNMENT_EXPIRED,
    TASK_AUTO_CLOSED,
    TASK_UPDATED,
    OFFER_UPDATED
}
